site_name: Supercritical CO2 Energy Storage (sCO2ES)
repo_url: https://github.com/VasuLab/sCO2ES
repo_name: VasuLab/sCO2ES
site_url: https://vasulab.github.io/sCO2ES/
copyright: "Copyright &copy; 2024 UCFRF, Inc. All Rights Reserved."

nav:
  - Overview:
    - index.md
  - Reference:
    - reference/index.md
    - Case Files: reference/case-files.md
    - Errors: reference/errors.md
    - Properties: reference/properties.md


theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - search.highlight
    - toc.follow
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
- search
- social
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_section_style: table
          members_order: source
          merge_init_into_class: True
          show_root_toc_entry: False
          show_source: False
          show_signature: False
          show_symbol_type_heading: True
          show_symbol_type_toc: True

watch:
  - sco2es

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
