name: main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:  # Update documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.3
      - name: Install dependencies
        run: poetry install --with docs
      - run: git fetch origin gh-pages --depth=1
      - name: Deploy docs
        run: mkdocs gh-deploy
